name: MyEssentials
main: craftforfood.myessentials.MyEssentials
version: 0.1

commands:
    buildtool:
        description: Tells the current build tool
        usage: /buildtool
        permission: myessentials.build
    mye:
        description: Information about MyEssentials
        usage: /mye
        permission: myessentials.mye
    sphere:
        description: Creates an sphere!
        usage: /sphere radius externalmaterial internalmaterial
        permission: myessentials.build.sphere
    zoneid:
        description: Changes de block inside selected zone to any id
        usage: /<command> id:data
        permission: myessentials.build.zoneid
    zonetop:
        description: Changes the upper slice of the current selection to any id
        usage: /<command> id:data
        permission: myessentials.build.zonetop
    zonefloor:
        description: Changes the lowest slice of the current selection to any id
        usage: /<command> id:data
        permission: myessentials.build.zonefloor
    zonewalls:
        description: Walls
        usage: /<command> id:data
        permission: myessentials.build.zonewalls
    zonebox:
        description: Creates a box with any id
        usage: /<command> id:data
        permission: myessentials.build.zonebox
    zoneselection:
        description: Copys selection
        usage: /zoneselection
        permission: myessentials.build.zoneselection
    zonepaste:
        description: Paste last cut/copy selection
        usage: /zonepaste <cut/copy>
        permission: myessentials.build.zonepaste